POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI1YzE0MmU2YWVkZGVmMzZjNTFlN2RmMzciLCJpYXQiOjE1NDQ4MjY0OTd9.X6Z9NWoRzJ7kzQSgreeK2g_F4pEp6u1MC5uZ2FS2BVI

{
  "title": "BEARER AUTH goes root2? post_api_blogs.rest talks",
  "author": "vaaPo",
  "url": "http://localhost:3003",
  "likes": 666
}