PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
content-type: application/json

{
  "id": "5a422a851b54a676234d17f7",
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7000
}
